# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Franklinfang
brief-intro: J2EE Server Engineer
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://frankdevhub.github.io" # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

# other links
github_username:  frankdevhub
email: frankdevhub@gmail.com

description_footer: 这世界上有三种人：羊，狼和牧羊犬，你自己选择。

comments: true

comment:
#disqus_shortname: 
#duoshuo_shortname: 
   gitalk: true
   gitalk_clientID: 'dd5d3058c9ed2d5835c6'
   gitalk_Secret: '3a64d23a737d67ebb98903b9af98e53889592573'
   gitalk_repo: 'frankdevhub.github.io'
   gitalk_owner: 'frankdevhub'
   gitalk_admin: 'frankdevhub'
   distractionFreeMode: true

# statistic analysis 
baidu_tongji_id: 4cbcf4f20c00cf6768989d0f363af2b8

# Share
social-share: true
social-share-items: ['wechat']

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 4000

# url
category_dir: category/
tag_dir: tag/
life_dir: life/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
plugins: [jekyll-paginate,jekyll-sitemap]
paginate: 6

# Google Map APi
google_map_api: https://maps.googleapis.com/maps/api/js?key=[API_KEY]&callback=initMap
google_map_api_cn: https://maps.google.cn/maps/api/js?key=[API_KEY]&callback=initMap
google_map_key: AIzaSyCFQKvF06HHSlm6BUeACn153xWu7ZQHujc
